### ISSUE TITLE
the link to moody in the readme appears broken

### ISSUE THREAD

**Issue by RallyTronics** [Afrostie/Mopviewer#3]

**Comment by Afrostie** [comment]
Ah, moody was made private while it under goes some major changes, I'll remove the link for now

**Comment by rucs-hack** [comment]
Ok, thanks for letting me know

**Comment by rucs-hack** [comment]
Oh wait, you mean mine, yes, I didn't think anyone was interested in it anyway, there've been no downloads, so I hid it until things were done as regards file formats and such.

**Comment by RallyTronics** [comment]
I have been playing around with what I assume is an older version of Moody I found on Github.  I added GLFW support and a rendering thread so that it renders to an opengl context instead of writing a mop file.  I will set it aside if you are making changes though.  Thanks!

**Comment by rucs-hack** [comment]
That version is rather out of date, yes. The mop file format needs a makeover to allow for compression and entry skipping. Given the view optimisations of Mopviewer (particle skipping), the originally planned compression technique is inadequate. It’s this that made me make Moody’s current repository private until my file writer and reader (which is shared with MopViewer) is updated and working. At present all I'm doing is producing test datasets for Andrew.

**Comment by rucs-hack** [comment]
moody is now public again. I haven't finished all the changes yet, but I've started.
I want to add in FaceBooks Folly library
https://github.com/facebook/folly
 and ditch the STD library, but I'm not there yet.

**Comment by Afrostie** [comment]
Ok, i added the link back in for the moment, I'll close this for now

**Comment by RallyTronics** [comment]
Thanks guys!
