### ISSUE TITLE
integrating MopViewers Mopfile reader with that in Moody

### ISSUE THREAD

**Issue by rucs-hack** [Afrostie/Mopviewer#4]
I've put the reader changes in Mopfile from MopViewer into Moody, and added my writer changes, so I beleive they are now unified.

The compression isn't yet integrated, I'm still unsure how I can do this in light of the particle skipping (too little time as ever).

Whatever I do will stiil be below what MopViewer accesses, but when done the two Mopreader codebases will need to be unified again.

This does lead me to think that Mop File handlng should be in its own distinct project, what do you think?

**Comment by Afrostie** [comment]
Having a separate repository makes sense to me, the loading has always been kept in an entirely separate mopLoader folder so it would be easy enough to have it in a distinct project

**Comment by rucs-hack** [comment]
I'll do it tomorrow, but on gitlab, not github, I prefer gitlab.

Sent from my iPad

On 6 Apr 2016, at 22:16, Andrew Frost <notifications@github.com<mailto:notifications@github.com>> wrote:


Having a separate repository makes sense to me, the loading has always been kept in an entirely separate mopLoader folder so it would be easy enough to have it in a distinct project

-

**Comment by Afrostie** [comment]
Fine by me, let me know the link if you get it done, i'll probably try and figure out submodules in git with it

**Comment by rucs-hack** [comment]
I'd like to link it to my code somehow so I don't have it in its own repository and my code at the same time, If you figure out how to do it, let me know. If you think having it on Github would make life easier for you I can do thatI guess, maybe even move Moody back too, but most of my stuff is staying on Gitlab, because I like it.

I can't promise I won't mutter about it and need consoling with Starbucks or anything, but I could do it.

**Comment by rucs-hack** [comment]
https://gitlab.com/carey.pridgeon/Mopfile

**Comment by Afrostie** [comment]
I've updated mopViewer to use the central repository for Mopfile instead of having a seperate copy, i think I have done it correctly using git submodule but it's hard to tell until there are some changes made to mopfile.

It all seems to work fine at the moment however

**Comment by rucs-hack** [comment]
Cool, I shall try that myself

**Comment by rucs-hack** [comment]
If you get a gitlab account I'll give you edit privileges on Mopfile

**Comment by Afrostie** [comment]
My gitlab is https://gitlab.com/u/Afrostie1

**Comment by rucs-hack** [comment]
I'm not so sure Submodules will work, since they use a fork, changes to that fork won't go back to the main repo. I'll have a think about this.
